FROM python:3.5-alpine


RUN apk add --update bash curl openssh && \
  rm -rf /var/cache/apk/*

# Install AWS command line tool
RUN pip install --upgrade pip && pip install awscli

RUN mkdir /project
WORKDIR /project

# Install Kubernetes
RUN curl -SLO https://github.com/kubernetes/kubernetes/releases/download/v1.2.0/kubernetes.tar.gz && \
  tar xzvf kubernetes.tar.gz && \
  rm kubernetes.tar.gz

ENV PATH /project/kubernetes/cluster:$PATH
ENV PATH /project/kubernetes/platforms/linux/amd64:$PATH

ADD init-cluster.sh /project

CMD "/bin/bash"
