apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: hello-app
    track: test
  name: hello-app-thrasher
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: hello-app
    spec:
      containers:
      - name: hello-app
        image: jdeskins/hello-node:thrasher
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80