apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: hello-app
    track: canary
  name: hello-app
spec:
  replicas: 4
  selector:
    matchLabels:
      run: hello-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: hello-app
        track: canary
    spec:
      containers:
      - name: hello-app
        image: jdeskins/hello-node:2.0
        ports:
        - containerPort: 8080