apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: hello-node
    track: stable
  name: hello-node
spec:
  replicas: 3
  selector:
    matchLabels:
      run: hello-node
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  minReadySeconds: 5
  template:
    metadata:
      labels:
        run: hello-node
        track: stable
    spec:
      containers:
      - name: hello-node
        image: jdeskins/hello-node:2.0
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "128Mi"
